import { 
  Navbar, 
  NavBody, 
  NavItems, 
  NavbarLogo,
  NavbarButton 
} from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* navbar */}
        <Navbar>
          <NavBody>
            <NavbarLogo />
            <NavItems 
              items={[
                { name: "Home", link: "/" },
                { name: "About", link: "/about" },
                { name: "Services", link: "/services" },
                { name: "Contact", link: "/contact" },
              ]} 
            />
            <NavbarButton href="/get-started">
              Get Started
            </NavbarButton>
          </NavBody>
        </Navbar>
      
       
        {children}
      </body>
    </html>
  );
}
